name: rallyx_modern
description: "Rally-X inspired game library built with Flutter + Flame + Forge2D."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.35.1
  flame_forge2d: ^0.19.2+4
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
